toc = true
author = "Javier"
avatar = "img/commons/avatar.jpg"

[assets]
  self_host = false

[social]
  name = "Javier Muñoz"
  url = "https://github.com/javiermf"

[[social.links]]
  type = "github"
  id = "javiermf"
  icon = "fab fa-github"

[[social.links]]
  type = "email"
  id = "javier.munoz@gmail.com"
  icon = "fas fa-envelope"

[[social.links]]
  type = "custom"
  id = "https://www.linkedin.com/in/javiermf"
  icon = "fab fa-linkedin"

[[social.links]]
  type = "rss"
  icon = "fas fa-rss"
