toc = true

[comments]
  enable = true
  provider = "giscus"
  [comments.giscus]
    repo = "JavierMF/yet-another-ai-blog"
    repo_id = "R_kgDOTEFt4A"
    category = "Announcements"
    category_id = "DIC_kwDOTEFt4M4C_5MP"
    mapping = "pathname"
    reactions_enabled = "1"
    input_position = "bottom"
author = "Javier"
avatar = "img/commons/avatar.jpg"

[assets]
  self_host = false

[social]
  name = "Javier Muñoz"
  url = "https://github.com/javiermf"

[[social.links]]
  type = "github"
  id = "javiermf"
  icon = "fab fa-github"

[[social.links]]
  type = "email"
  id = "javier.munoz@gmail.com"
  icon = "fas fa-envelope"

[[social.links]]
  type = "custom"
  id = "https://www.linkedin.com/in/javiermf"
  icon = "fab fa-linkedin"

[[social.links]]
  type = "rss"
  icon = "fas fa-rss"
